version: "3.9"

services:
  aws-step-functions-local:
    container_name: aws-step-functions-local
    image: amazon/aws-stepfunctions-local:latest
    ports:
      - "8083:8083"
    environment:
      - AWS_ACCESS_KEY_ID=access_key
      - AWS_SECRET_ACCESS_KEY=secret_key
      - AWS_REGION=eu-central-1
      - LAMBDA_ENDPOINT=http://host.docker.internal:3001
    networks:
      - sam-network
networks:
  sam-network:
    name: sam-network
