version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - npm install
      - npm install -g aws-cdk
  build:
    commands:
      - npm install
      - npm run test
      - npm run cdk:synth

artifacts:
  base-directory: infra/cdk.out
  files:
    - '**/*'