version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - npm install
  build:
    commands:
      - cd infra
      - npm install
      - npm run cdk -- synth

artifacts:
  base-directory: infra/cdk.out
  files:
    - '**/*'