version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - npm install
  build:
    commands:
      - npm run test:infra
      - npm run cdk:synth

artifacts:
  base-directory: infra/cdk.out
  files:
    - '**/*'

reports:
  jest_reports:
    files:
      - test-report.xml
    file-format: JUNITXML
    base-directory: infra/test-reports